# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "0a3c45d6-65af-40da-bb6b-64f63f8f7091"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # cocoapods

  # build your iOS app
  build_app(
    # scheme: "YourScheme",
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
